---
- hosts: localhost
  environment:
   no_proxy: 10.87.170.10
  collections:
    - netapp.ontap
  gather_facts: false
  name: Create FC Igroup
  tasks:
  - name: Create FC Igroup
    na_ontap_igroup:
      state: present
      name: "{{ item.igroup_name }}"
      initiator_group_type: "{{ item.group_type }}"
      os_type: "{{ item.os_type }}"
      vserver: "{{ item.vserver }}"
      initiators: "{{ item.initiators }}"
      hostname: "{{ hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
    loop:
      - { igroup_name: 'na777vmw001', group_type: 'fcp', os_type: 'linux', vserver: 'st024vs', initiators: '20:FA:00:25:B5:0A:00:00,20:FA:00:25:B5:0B:00:00' }
      - { igroup_name: 'na777vmw002', group_type: 'fcp', os_type: 'linux', vserver: 'st024vs', initiators: '20:FA:00:25:B5:0A:00:01,20:FA:00:25:B5:0B:00:01' }
      - { igroup_name: 'na777vmw003', group_type: 'fcp', os_type: 'linux', vserver: 'st024vs', initiators: '20:FA:00:25:B5:0A:00:02,20:FA:00:25:B5:0B:00:02' }
      - { igroup_name: 'na777vmw004', group_type: 'fcp', os_type: 'linux', vserver: 'st024vs', initiators: '20:FA:00:25:B5:0A:00:03,20:FA:00:25:B5:0B:00:03' }
      - { igroup_name: 'na777vmw005', group_type: 'fcp', os_type: 'linux', vserver: 'st024vs', initiators: '20:FA:00:25:B5:0A:00:04,20:FA:00:25:B5:0B:00:04' }
      - { igroup_name: 'na777vmw006', group_type: 'fcp', os_type: 'linux', vserver: 'st024vs', initiators: '20:FA:00:25:B5:0A:00:05,20:FA:00:25:B5:0B:00:05' }
      - { igroup_name: 'na777vmw007', group_type: 'fcp', os_type: 'linux', vserver: 'st024vs', initiators: '20:FA:00:25:B5:0A:00:06,20:FA:00:25:B5:0B:00:06' }
      - { igroup_name: 'na777vmw008', group_type: 'fcp', os_type: 'linux', vserver: 'st024vs', initiators: '20:FA:00:25:B5:0A:00:07,20:FA:00:25:B5:0B:00:07' }
      - { igroup_name: 'na777vmw009', group_type: 'fcp', os_type: 'linux', vserver: 'st024vs', initiators: '20:FA:00:25:B5:0A:00:08,20:FA:00:25:B5:0B:00:08' }
      - { igroup_name: 'na777vmw010', group_type: 'fcp', os_type: 'linux', vserver: 'st024vs', initiators: '20:FA:00:25:B5:0A:00:09,20:FA:00:25:B5:0B:00:09' }
      - { igroup_name: 'na777vmw011', group_type: 'fcp', os_type: 'linux', vserver: 'st024vs', initiators: '20:FA:00:25:B5:0A:00:0A,20:FA:00:25:B5:0B:00:0A' }
      - { igroup_name: 'na777vmw012', group_type: 'fcp', os_type: 'linux', vserver: 'st024vs', initiators: '20:FA:00:25:B5:0A:00:0B,20:FA:00:25:B5:0B:00:0B' }
      - { igroup_name: 'na777vmw013', group_type: 'fcp', os_type: 'linux', vserver: 'st024vs', initiators: '20:FA:00:25:B5:0A:00:0C,20:FA:00:25:B5:0B:00:0C' }
      - { igroup_name: 'na777vmw014', group_type: 'fcp', os_type: 'linux', vserver: 'st024vs', initiators: '20:FA:00:25:B5:0A:00:0D,20:FA:00:25:B5:0B:00:0D' }
      - { igroup_name: 'na777vmw015', group_type: 'fcp', os_type: 'linux', vserver: 'st024vs', initiators: '20:FA:00:25:B5:0A:00:0E,20:FA:00:25:B5:0B:00:0E' }
      - { igroup_name: 'na777vmw016', group_type: 'fcp', os_type: 'linux', vserver: 'st024vs', initiators: '20:FA:00:25:B5:0A:00:0F,20:FA:00:25:B5:0B:00:0F' }
