---
- hosts: localhost
  environment:
   no_proxy: 10.87.170.10
  collections:
    - netapp.ontap
  gather_facts: false
  name: Loop of LUN creation
  tasks:
  - name: Create LUN
    na_ontap_lun:
      state: present
      name: "{{ item.lun_name }}"
      size: "{{ item.lun_size }}"
      size_unit: "{{ item.volume_size_unit }}"
      vserver: "{{ item.vserver }}"
      flexvol_name: "{{ item.flexvol_name }}"
      hostname: "{{ hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
    loop:
      - { lun_name: 'na777vmw001', lun_size: '16', volume_size_unit: 'gb', vserver: 'st024vs', flexvol_name: 'st024vs_vol1' }
      - { lun_name: 'na777vmw002', lun_size: '16', volume_size_unit: 'gb', vserver: 'st024vs', flexvol_name: 'st024vs_vol1' }
      - { lun_name: 'na777vmw003', lun_size: '16', volume_size_unit: 'gb', vserver: 'st024vs', flexvol_name: 'st024vs_vol1' }
      - { lun_name: 'na777vmw004', lun_size: '16', volume_size_unit: 'gb', vserver: 'st024vs', flexvol_name: 'st024vs_vol1' }
      - { lun_name: 'na777vmw005', lun_size: '16', volume_size_unit: 'gb', vserver: 'st024vs', flexvol_name: 'st024vs_vol1' }
      - { lun_name: 'na777vmw006', lun_size: '16', volume_size_unit: 'gb', vserver: 'st024vs', flexvol_name: 'st024vs_vol1' }
      - { lun_name: 'na777vmw007', lun_size: '16', volume_size_unit: 'gb', vserver: 'st024vs', flexvol_name: 'st024vs_vol1' }
      - { lun_name: 'na777vmw008', lun_size: '16', volume_size_unit: 'gb', vserver: 'st024vs', flexvol_name: 'st024vs_vol1' }
      - { lun_name: 'na777vmw009', lun_size: '16', volume_size_unit: 'gb', vserver: 'st024vs', flexvol_name: 'st024vs_vol1' }
      - { lun_name: 'na777vmw010', lun_size: '16', volume_size_unit: 'gb', vserver: 'st024vs', flexvol_name: 'st024vs_vol1' }
      - { lun_name: 'na777vmw011', lun_size: '16', volume_size_unit: 'gb', vserver: 'st024vs', flexvol_name: 'st024vs_vol1' }
      - { lun_name: 'na777vmw012', lun_size: '16', volume_size_unit: 'gb', vserver: 'st024vs', flexvol_name: 'st024vs_vol1' }
      - { lun_name: 'na777vmw013', lun_size: '16', volume_size_unit: 'gb', vserver: 'st024vs', flexvol_name: 'st024vs_vol1' }
      - { lun_name: 'na777vmw014', lun_size: '16', volume_size_unit: 'gb', vserver: 'st024vs', flexvol_name: 'st024vs_vol1' }
      - { lun_name: 'na777vmw015', lun_size: '16', volume_size_unit: 'gb', vserver: 'st024vs', flexvol_name: 'st024vs_vol1' }
      - { lun_name: 'na777vmw016', lun_size: '16', volume_size_unit: 'gb', vserver: 'st024vs', flexvol_name: 'st024vs_vol1' }
