---
- hosts: localhost
  environment:
   no_proxy: 10.87.170.10
  collections:
    - netapp.ontap
  gather_facts: false
  name: Loop of LUN creation
  tasks:     
  - name: Add initiators to an igroup
  na_ontap_igroup_initiator:
    names: abc.test:def.com,def.test:efg.com
    initiator_group: test_group
    vserver: st024vs
    hostname: "{{ hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: false
