---
- hosts: localhost
  environment:
   no_proxy: 10.87.170.10
  collections:
    - netapp.ontap
  gather_facts: false
  name: Loop of LUN creation
  tasks:
   - name: Create LUN
    na_ontap_lun:
      state: present
      name: "{{ item.lun_name }}"
      size: "{{ item.lun_size }}"
      size_unit: "{{ item.volume_size_unit }}"
      vserver: "{{ item.vserver }}"
      flexvol_name: "{{ item.flexvol_name }}"
      hostname: "{{ hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
    loop:
      - { lun_name: 'na777vmw001', lun_size: '16', volume_size_unit: 'gb', vserver: 'st024vs', flexvol_name: 'st024vs_vol1' }
