---
- hosts: localhost
  environment:
   no_proxy: 10.87.170.10
  collections:
    - netapp.ontap
  gather_facts: false
  name: Create FC Igroup
  tasks:
  - name: Create FC Igroup
    na_ontap_igroup:
      state: present
      name: "{{ item.igroup_name }}"
      initiator_group_type: "{{ item.group_type }}"
      os_type: "{{ item.os_type }}"
      vserver: "{{ item.vserver }}"
      initiators: "{{ item.initiators }}"
      hostname: "{{ hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
    loop:
      - { igroup_name: 'na777vmw001', group_type: 'fcp', os_type: 'linux', vserver: 'st024vs', initiators: '20:FA:00:25:B5:0A:00:00,20:FA:00:25:B5:0B:00:00' }
