---
- hosts: localhost
  environment:
   no_proxy: 10.87.170.10
  name: Setup ONTAP
  collections:
    - netapp.ontap
  tasks:
  - name: Create volume
    na_ontap_volume:
      state: present
      name: "st024vs_vol1"
      aggregate_name: "nolorna14st_01_nvm15t_01"
      size: "300" 
      size_unit: gb
      junction_path: "/st024vs_vol1"
      space_guarantee: "none"
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
