---
- hosts: localhost
  environment:
   no_proxy: 10.87.170.10
  name: Setup ONTAP
  collections:
    - netapp.ontap
  tasks:
  - name: Create volume
    na_ontap_volume:
      state: present
      name: "{{ volname }}"
      aggregate_name: "{{ aggr }}"
      size: "{{ size }}" 
      size_unit: gb
      junction_path: "/{{ volname }}"
      space_guarantee: "none"
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
  - name: Create LUN
    na_ontap_lun:
      state: present
      vserver: "{{ vserver }}"
      name: "{{ volname }}_01"
      flexvol_name: "{{ volname }}"
      size: "{{ size }}"
      size_unit: gb
      ostype: "{{ ostype }}"
      space_reserve: False
      https: true
      validate_certs: false
      hostname: "{{ hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
