---
- hosts: localhost
  environment:
    no_proxy: 10.87.170.10
  collections:
    - netapp.ontap
  gather_facts: false
  name: Loop of volume creation
  tasks:
  - name: "Gather current epoch time"
    set_fact:
      epoch_current_time: "{{ lookup('pipe', 'date +\"%s\"') }}"
  - name: "Set fact that will be the threshold for deleting snapshots"
    set_fact:
      remove_snapshots_after_epoch_time: "{{ (epoch_current_time | int) - (ontap_snapshot_prod_retention_days * 24 * 60 * 60) }}"
  - name: "{{ this_svm }} : {{ this_volume }} : Gather Snapshot Information for snapshots that are expired"
    netapp.ontap.na_ontap_info:
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      vserver: "{{ this_svm }}"
      https: yes
      validate_certs: false
      gather_subset:
        - snapshot_info
      query:
        snapshot-info:
          volume: "{{ this_volume }}"
          snapmirror-label: "{{ ontap_snapshot_snapmirror_label }}"
          access-time: "<{{ remove_snapshots_after_epoch_time }}" # Return all snapshots that have an access time older than the threshold (epoch number is less)
      desired_attributes:
        snapshot-info:
          snapmirror-label:
          access-time:
    register: snapshot_info
