---
- hosts: localhost
  environment:
   no_proxy: 10.87.170.10
  collections:
    - netapp.ontap
  gather_facts: false
  vars:
    login: &login
      hostname: "10.87.170.10"
      username: " {{ netapp_username }} "
      password: " {{ netapp_password }} "
      https: true
      validate_certs: false
  name: Onboard SVM
  tasks:
  - name: Create SVM
    na_ontap_svm:
      state: present
      name: "st024vs"
      root_volume: "st024vs_root"
      root_volume_aggregate: nolorna14st_01_nvm15t_01
      root_volume_security_style: unix
      comment: "NIMBUS PRI: Nimbus NO LOR ESX-boot"
      allowed_protocols: "fcp"
      <<: *login
